### PR TITLE
Adding New Schedule (urgent)

### PR DESCRIPTION
**Pull request by hacker-hippo**
Add ASAP, please! I procrastinated and forgot to add this schedule to prepare for a thing tomorrow.

### CODE REVIEW

**Comment by arjunpat** [comment]
Gotchu! Should be live relatively soon.

**Comment by arjunpat** [comment]
Just curious: it looks like you removed all the other future calendar events. Is there a specific reason for doing so or is that an error?

**Comment by hacker-hippo** [comment]
There is a reason... I was using an out of date calendar for my school. I will ratify a new schedule in the future! Thanks so much.

**Comment by arjunpat** [comment]
Ok, awesome. Just to clarify, you put the custom schedule for today, September 24th. Did you mean to put it for tomorrow, Friday, September 25th?

**Pull request merged**
