### PR TITLE
Fixing Monday being Sunday (I think)

### PR DESCRIPTION
**Pull request by isamuishiii**
It was showing Monday as weekend

### CODE REVIEW

**Comment by isamuishiii** [comment]
Sorry, I'm new to yml and didn't know how it would start and end :(

**Comment by arjunpat** [comment]
Fixed.

**Comment by isamuishiii** [comment]
When should it be live?

**Comment by arjunpat** [comment]
It should be live now. It takes about 6 hours for caches to clear on all computers. You will have to "hard reload" to see the changes immediately.

**Pull request merged**
